import Link from "next/link";
import { Clock, BarChart2 } from "lucide-react";
import { Recipe } from "@/types";
import RecipeImage from "@/components/RecipeImage";

export default function RecipeCard({ recipe }: { recipe: Recipe }) {
  // Use local image path generated by Ollama
  const localImage = `/recipes/${recipe.slug}.png`;
  
  // Fallback AI image generation if local fails
  const encodedPrompt = encodeURIComponent(recipe.imagePrompt + ", high quality, artistic painting");
  const fallbackAiImage = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=800&height=600&seed=${recipe.id}&nologo=true`;

  return (
    <Link 
      href={`/recipe/${recipe.slug}`}
      className="group bg-white rounded-4xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300 hover:-translate-y-2 border-2 border-transparent hover:border-playful-yellow"
    >
      <div className="relative aspect-[4/3] overflow-hidden bg-gray-100">
        <RecipeImage 
          src={localImage}
          fallbackSrc={fallbackAiImage}
          alt={recipe.title}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
        />
        <div className="absolute top-4 right-4 bg-playful-green text-white px-3 py-1 rounded-full text-xs font-bold shadow-md">
          {recipe.difficulty}
        </div>
      </div>
      
      <div className="p-6">
        <h3 className="text-xl font-black text-gray-800 mb-2 group-hover:text-playful-orange transition-colors">
          {recipe.title}
        </h3>
        <p className="text-gray-500 text-sm line-clamp-2 mb-4 leading-relaxed">
          {recipe.description}
        </p>
        
        <div className="flex items-center gap-4 text-gray-400 text-xs font-bold">
          <div className="flex items-center gap-1">
            <Clock className="w-4 h-4 text-playful-blue" />
            <span>{recipe.prepTime + recipe.cookTime} דק׳</span>
          </div>
          <div className="flex items-center gap-1">
            <BarChart2 className="w-4 h-4 text-playful-pink" />
            <span>{recipe.ingredients.length} רכיבים</span>
          </div>
        </div>
      </div>
    </Link>
  );
}
